name: Feature request
description: Suggest an idea
title: "Feature Request: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Before requesting formatting for copypastes from a specific website or app, please be aware that there are literally hundreds websites and apps, and it will therefore be impossible to implement all of them. This plugin's goal is therefore to focus on the most common ones.
  - type: textarea
    id: feature-requested
    attributes:
      label: Feature Requested
      description: A clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain the request.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: The feature would be useful to more users than just me.
          required: true

